### PR TITLE
Normalize all config paths

### LINKED ISSUE #985: Normalize paths in settings
This is not a bug, more an inconsistency with the settings.

I can set the location of my eslintrc file with a tilde like so:

```
~/.eslintrc
```

However, setting the Global Node Installation Path to

```
~/.config/yarn/global
```

does not work, but

```
/Users/mickyginger/.config/yarn/global
```
works fine

### PR DESCRIPTION
**Pull request by Arcanemagus**
Enhance all paths in the configurations so that they allow the use of `~` where appropriate.

Fixes #985.

### CODE REVIEW

**Comment by skylize** [comment]
Where is that config defined? Couldn't we just do something like this when we first grab it?
```
config.globalNodePath = globalNodePath.replace(/^~/, process.env.HOME)
```

**Comment by Arcanemagus** [comment]
Right now the entire `linter-eslint` config is sent in with each job request. Re-working how the configuration is handled is on my to-do list, but for now I kept this PR minimal to work within the framework as it currently exists.

File: src/worker-helpers.js [hunk 1]
```diff
@@ -13,6 +13,12 @@ const Cache = {
   LAST_MODULES_PATH: null
 }
 
+const cleanPath = (path) => {
```
Comment (IanVS) [inline src/worker-helpers.js]: __*Preference*__

It might be good to drop a small docblock here to explain what this is doing to clean up the path.

File: src/worker-helpers.js [hunk 2]
```diff
@@ -13,6 +13,12 @@ const Cache = {
...
+  const unTildeify = fs.normalize(path)
+  const unEnvVarify = resolveEnv(unTildeify)
```
Comment (IanVS) [inline src/worker-helpers.js]: __*Preference*__

Having an ending of `ify` makes me think that these variables are functions, but it seems that they are actually just strings.  Honestly, I think you could just combine these three lines into:

```js
return resolveEnv(fs.normalize(path));
```

File: src/worker-helpers.js [hunk 3]
```diff
@@ -45,7 +51,8 @@ export function findESLintDirectory(modulesDir, config, projectPath) {
   let locationType = null
   if (config.useGlobalEslint) {
     locationType = 'global'
-    const prefixPath = config.globalNodePath || getNodePrefixPath()
+    const configGlobal = config.globalNodePath && cleanPath(config.globalNodePath)
```
Comment (IanVS) [inline src/worker-helpers.js]: __*Minor Suggestion*__

You could avoid the awkward `&&` here if `cleanPath` was changed to handle a falsey argument by just returning it unchanged or returning `null` or something.  It might not be a bad idea to add such a check to it no matter what, although I'm not sure what it does now with falsey values, maybe it already does.

File: src/worker-helpers.js (hunk 2 above)
Comment (Arcanemagus) [reply src/worker-helpers.js]: I think I was thinking of `ified`.

File: src/worker-helpers.js (hunk 3 above)
Comment (Arcanemagus) [reply src/worker-helpers.js]: I'm guessing it would have thrown a `TypeError` somewhere in there. If it's falsy I just made it return an empty string. (`null` would have caused errors when used in `path.*` functions.)
