### PR TITLE
Better `eslint` lookup

### LINKED ISSUE #294: error with extends local config having sublevels of node_modules folders
In v5.2.0 i have one case where i'm still getting the error using local plugin extends.

I'm working in a browserify project where i have the next folder structure:
```
node_modules/
src/
    components/
    styles/
    node_modules/
    index.js
.eslintrc
gulpfile.js
package.json
```
If i check the gulpfile.js with atom-eslint everthing works great. But if i check the src/index.js atom-eslint is trying to find the eslint config plugin in src/node_modules/ instead of the root node_modules, throwing the error: Cannot find module 'eslint-config-airbnb'

Note: in v4.0.0 is working fine.

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #294 and my case outlined in #350 as well. It's an improved version of #350 after some discussion, specifically, it does not rely on presence of `package.json` in sub-projects - #350 was assuming they are not defined, which seems to be only applicable to browserify projects.

It essentially works in the same way as lookup for `.eslintrc` - find the closest `node_modules/eslint` folder starting from the `fileDir` and moving up.

The feature is in lines 15-17, the rest is just styling tweaks - early return to make it easier to reason about and better scoping of variables.

Tested in failing projects with `babel-eslint` and `eslint-plugin-react` plugins.

CC: @Arcanemagus - sorry for the delay! Almost forgot about that. Commit(s) to be rebased once approved / discussed / whatever!

To clarify, that PR makes projects following `babel-like` structure work again, that is:
```
./.eslintrc
./node_modules/eslint
./packages/core/node_modules/...
./packages/web/node_modules/...
```
so editing files inside sub-project with its own `node_modules` won't fail, because we will locate them in the umbrella outer package.

See https://github.com/babel/babel/blob/master/package.json#L16 for real life example.

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-eslint/396)

### CODE REVIEW

File: lib/es5-helpers.js [hunk 1]
```diff
@@ -9,35 +9,27 @@ let prefixPath = null
 const parentPath = FS.realpathSync(Path.join(__dirname, '..'))
 const atomEslintPath = Path.join(parentPath, 'node_modules', 'eslint')
 
+// Find directory of eslint installation. Traverse up the tree checking every
+// `node_modules` directory
 function findEslintDir(params) {
-  const modulesPath = find(params.fileDir, 'node_modules')
-  let eslintNewPath = null
+  if (!params.global) {
+    return find(params.fileDir, 'node_modules/eslint') || atomEslintPath
```
Comment (grabbou) [inline lib/es5-helpers.js]: It turns out that it will keep looking up the tree or return null if it does not exist, so that's the old behaviour of `try catch` we had.

Comment (steelbrain) [inline lib/es5-helpers.js]: I don't think the `find` method supports `node_modules/eslint`, `eslint` would work though

**Comment by Arcanemagus** [comment]
Can you include specs to test this functionality? Specifically they should be failing before, and working after this patch is applied (and of course match what `eslint` itself does in the terminal :stuck_out_tongue:).

Just including the 3 spec files from #350 should cover the use cases it was originally handling.

File: lib/es5-helpers.js (hunk 1 above)
Comment (grabbou) [inline lib/es5-helpers.js]: It seemd to work when I was debugging. with `eslint` it won't go inside `node_modules`, would it?

**Comment by grabbou** [comment]
Ahh, all right! I was looking at test cases in your PR but what I've only seen were empty files - now I know their purpose! Updating :)

File: lib/es5-helpers.js [hunk 2]
```diff
@@ -9,35 +9,27 @@ let prefixPath = null
 const parentPath = FS.realpathSync(Path.join(__dirname, '..'))
 const atomEslintPath = Path.join(parentPath, 'node_modules', 'eslint')
 
+// Find directory of eslint installation. Traverse up the tree checking every
+// `node_modules` directory
 function findEslintDir(params) {
-  const modulesPath = find(params.fileDir, 'node_modules')
-  let eslintNewPath = null
+  if (!params.global) {
+    return find(params.fileDir, ['node_modules', 'eslint'].join(Path.sep)) || atomEslintPath
```
Comment (grabbou) [inline lib/es5-helpers.js]: Looks like it does -> https://github.com/AtomLinter/atom-linter/blob/master/src/helpers.js#L210. Since it splits by Path.sep - rewrote that from `node_modules/eslint` to join(Path.sep) so it's always split correctly into chunks.

**Comment by grabbou** [comment]
Update: Squashed & reordered so there's failing test suite commit before actual implementation.

**Comment by Arcanemagus** [comment]
@AtomLinter/linter-eslint This is looking good to me, anyone else have any comments?

**Comment by Arcanemagus** [comment]
Got confirmation from @steelbrain in chat that this looks good to him, with no other comments I'm merging this in :stuck_out_tongue:.

**Comment by grabbou** [comment]
Tkanks! Hopefully that wasn't my last PR! :D
