### PR TITLE
Add `Fix on Save option` to fix lint errors on save ( fixes #417)

### LINKED ISSUE #417: Fix on save
It will be great if there was an option to fix the file onsave.

### PR DESCRIPTION
**Pull request by pvamshi**
~~**DO NOT MERGE** 
Need to fix the unit test . I could not figure out how to write the unit test which checks something after the file is saved. I used setTimeOut as an ugly hack , but somone please help.~~
I wish to handle unit tests in another task if its fine. Otherwise we can keep this pull request open for a while till we can get the unit test . 

**Main change** : 

1. Added new option (`boolean`) to check if we need to fix the errors on save. Default is `false`
image

2. Everytime a file is opened, an observer to save event is added, on save we check if config is true then call fix errors job
3. If fixing is success, we stay quiet . If an exceptions happens, we report .

### CODE REVIEW

**Comment by pvamshi** [comment]
I removed the test case as it looked time consuming to me. I need to understand atom environment in more detail. I might create another task . Its too exciting to see errors fix on save, so I would like to push the code. Please decide on this and proceed accordingly.

File: lib/main.js [hunk 1]
```diff
@@ -63,6 +63,12 @@ module.exports = {
       description: 'Paths of node_modules, .eslintignore and others are cached',
       type: 'boolean',
       default: false
+    },
+    fixOnSave: {
+      title: 'Fix errors on save',
+      description: 'Everytime the file is saved, linter-eslint tries to fix errors',
```
Comment (Arcanemagus) [inline lib/main.js]: Maybe change this to something like: "Have eslint attempt to fix some errors automatically when saving the file."?

File: src/main.js [hunk 2]
```diff
@@ -56,6 +56,12 @@ module.exports = {
       description: 'Paths of node_modules, .eslintignore and others are cached',
       type: 'boolean',
       default: false
+    },
+    fixOnSave: {
+      title: 'Fix errors on save',
+      description: 'Everytime the file is saved, linter-eslint tries to fix errors',
```
Comment (Arcanemagus) [inline src/main.js]: Maybe change this to something like: "Have eslint attempt to fix some errors automatically when saving the file."?

File: src/main.js [hunk 3]
```diff
@@ -86,7 +105,6 @@ module.exports = {
           atom.notifications.addError('Linter-ESLint: Please save before fixing')
           return
         }
-
```
Comment (Arcanemagus) [inline src/main.js]: Any reason this was cut? vertical whitespace itself isn't bad, just too much of it :wink:

**Comment by Arcanemagus** [comment]
What issues are you having with writing specs? I'd much rather they were added in this PR as otherwise we are just expanding the area of untested code :disappointed:.

**Comment by pvamshi** [comment]
I strongly agree it should go with this code . But I am not entirely sure how it should be written, should we mock the request and trigger save event , we also need to trigger open editor event . I am not quite familiar with atom yet, so I will need time to write them .

**Comment by Arcanemagus** [comment]
[This block](https://github.com/AtomLinter/linter-eslint/blob/v7.1.3/spec/linter-eslint-spec.js#L32-L38) shows how to open a file and get the resultant editor.

The way I think I would go about this is copy/create a temp file in the OS's temp directory (use a module for this?), open it in Atom and trigger the save, then read back the contents and see if the appropriate fix was applied.

**Comment by pvamshi** [comment]
I tried the same . I was stuck at the save part. How to know the save is done , save method is not giving any promise right ?

**Comment by Arcanemagus** [comment]
If the save method doesn't return a promise then it's synchronous so you just need to run it and execution will block on that. I think you can just wrap it in a `waitsForPromise` even if it doesn't return a Promise, haven't tested that though.

**Comment by pvamshi** [comment]
May be its not async, don't know why I thought it would be async by default. 
I will check revert back the deleted test case, probably its correct. 
```js
 describe('Fix errors when saved', () => {		
    beforeEach(() => {		
      atom.config.set('linter-eslint.fixOnSave', true)		
    })		
    it('should fix lint errors when saved', () => {		
      waitsForPromise(() =>		
        atom.workspace.open(fixPath).then(editor => {		
          lint(editor).then(messages => {		
            expect(messages.length).toEqual(2)		
              editor.save()		
              lint(editor).then(messages => {		
                expect(messages.length).toEqual(0)		
              })		
            })		
        })		
      )		
    })		
  })
```

**Comment by pvamshi** [comment]
I will squash the commits , if this looks OK :+1:

File: spec/linter-eslint-spec.js [hunk 4]
```diff
@@ -141,4 +141,23 @@ describe('The eslint provider for Linter', () => {
...
+    })
+    it('should fix lint errors when saved', () => {
+      waitsForPromise(() =>
+        atom.workspace.open(fixPath).then(editor => {
+          lint(editor).then(messages => {
+            expect(messages.length).toEqual(2)
+            editor.save()
+            lint(editor).then(messagesAfterSave => {
+              expect(messagesAfterSave.length).toEqual(0)
+            })
```
Comment (Arcanemagus) [inline spec/linter-eslint-spec.js]: Replace the file contents afterwards, this isn't an issue for CI builds, but if you are testing locally this will cause a change in the repo state :wink:.

**Comment by Arcanemagus** [comment]
A few comments that need to be addressed.

File: spec/linter-eslint-spec.js (hunk 4 above)
Comment (pvamshi) [inline spec/linter-eslint-spec.js]: I thought of this , but it was not showing any problem. I deliberately ran the test cases multiple times , they still work . The real file is not changed .

**Comment by pvamshi** [comment]
I updated the config message. The file contents is not giving any issue, should I still consider replacing the original file?

**Comment by Arcanemagus** [comment]
Really? That's odd... it must not be actually saving then??

**Comment by pvamshi** [comment]
Its total mystery to me honestly , it gave this error before saving. I deliberately said , expect 0 errors and message to be empty object. This was the output : 
```
  getESLintInstance && getESLintFromDirectory
    it tries to find a global eslint if config is specified
      Expected 2 to equal 0.
        Error: Expected 2 to equal 0.
        at /home/vamshi/projects/linter-eslint/spec/linter-eslint-spec.js:153:37
        at process._tickCallback (node.js:368:9)
      Expected [ { filePath : '/home/vamshi/projects/linter-eslint/spec/fixtures/files/fix.js', type : 'Error', range : [ [ 0, 11 ], [ 0, 12 ] ], text : 'Extra semicolon.', fix : { range : { start : { row : 0, column : 11 }, end : { row : 0, column : 12 } }, newText : '' } }, { filePath : '/home/vamshi/projects/linter-eslint/spec/fixtures/files/fix.js', type : 'Error', range : [ [ 2, 1 ], [ 2, 15 ] ], text : 'Expected indentation of 2 space characters but found 1.', fix : { range : { start : { row : 2, column : 1 }, end : { row : 2, column : 1 } }, newText : ' ' } } ] to be {  }.
        Error: Expected [ { filePath : '/home/vamshi/projects/linter-eslint/spec/fixtures/files/fix.js', type : 'Error', range : [ [ 0, 11 ], [ 0, 12 ] ], text : 'Extra semicolon.', fix : { range : { start : { row : 0, column : 11 }, end : { row : 0, column : 12 } }, newText : '' } }, { filePath : '/home/vamshi/projects/linter-eslint/spec/fixtures/files/fix.js', type : 'Error', range : [ [ 2, 1 ], [ 2, 15 ] ], text : 'Expected indentation of 2 space characters but found 1.', fix : { range : { start : { row : 2, column : 1 }, end : { row : 2, column : 1 } }, newText : ' ' } } ] to be {  }.
        at /home/vamshi/projects/linter-eslint/spec/linter-eslint-spec.js:154:30
        at process._tickCallback (node.js:368:9)
```

**Comment by Arcanemagus** [comment]
Rebase on master before you squash btw, looks like this was originally branched off of 0203b38bd5c206b5b992c0e10028ccb1161928ee :stuck_out_tongue:.

**Comment by pvamshi** [comment]
@Arcanemagus I did rebase and squashed. Can you trigger the build again please. 
Let me know if there is anything I missed, otherwise we can merge.

**Comment by Arcanemagus** [comment]
This LGTM, and we haven't had anyone else pipe up with changes so I'm merging this, thanks for putting this together!

**Comment by pvamshi** [comment]
@Arcanemagus Thankyou. 
When will be the next release? 
Whole team at my work is waiting for this fix :)

**Comment by jamesdixon** [comment]
@pvamshi nice work!

**Comment by Arcanemagus** [comment]
Looks like we aren't getting input from the rest of @AtomLinter/linter-eslint so I'll go ahead and push out a minor version with this in a few minutes.

**Comment by IanVS** [comment]
Didn't realize you were looking for input.  Anything in particular you wanted us to look at?

**Comment by Arcanemagus** [comment]
Anything else that needs to go into that release? Tried contacting on Slack but it seems nobody reads that :stuck_out_tongue: (Also I _may_ have forgotten about this myself over the weekend...)

**Comment by IanVS** [comment]
Ah, missed the slack.  I've set up desktop notifications on that channel now.  Looks like the other PRs need to be rebased before they can be merged, but it would be good to get this one out there in the wild.

**Comment by Arcanemagus** [comment]
Yep, the other two need more work before merging. I'll get this released in a few minutes then.

**Comment by Arcanemagus** [comment]
Published in v7.2.0 :tada:.

**Comment by kentcdodds** [comment]
I'm not seeing it :-( Am I missing something?

screen shot 2016-04-18 at 9 04 17 am

**Comment by jamesdixon** [comment]
Try restarting atom. That seemed to work for me
