### PR TITLE
Fix behavior when endColumn or endLine is null

### LINKED ISSUE #1197: Invalid position given by 'jsdoc/no-undefined-types'
ESLint returned a point that did not exist in the document being edited.
Rule: `jsdoc/no-undefined-types`
Requested start point: 715:0 - 715:0

Debug information:
```json
{
  "atomVersion": "1.32.0",
  "linterEslintVersion": "8.4.1",
  "linterEslintConfig": {
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDirs": [],
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": [],
    "ignoreFixableRulesWhileTyping": false
  },
  "eslintVersion": "5.9.0",
  "hoursSinceRestart": 18.6,
  "platform": "darwin",
  "eslintType": "local project",
  "eslintPath": "/Users/ganesha/Documents/ohcm/ohcm-fan-service/node_modules/eslint",
  "editorScopes": [
    "source.js",
    "keyword.control"
  ]
}
```

### PR DESCRIPTION
**Pull request by mattlyons0**
Fixes #1197, #1196, #1195, #1192 

The JSDoc plugin returns `null` when there isn't a end column. The ESLint API docs specifically say the type of `endColumn` and `endLine` are optional or must be a `number`, therefore it is probably more correct and safer to do that check instead of a undefined check: https://eslint.org/docs/developer-guide/working-with-plugins

### CODE REVIEW

File: src/helpers.js [hunk 1]
```diff
@@ -274,7 +274,7 @@ export async function processESLintMessages(messages, textEditor, showRule) {
      keep doing so in later uses.
      */
     const msgLine = line - 1
-    if (typeof endColumn !== 'undefined' && typeof endLine !== 'undefined') {
+    if (typeof endColumn === 'number' && typeof endLine !== 'number') {
```
Comment (IanVS) [inline src/helpers.js]:
```suggestion
    if (typeof endColumn === 'number' && typeof endLine === 'number') {
```

Comment (mattlyons0) [reply src/helpers.js]: Woops, nice catch.
I've force pushed so a new commit isn't created just for that fix.

**Comment by mattlyons0** [comment]
Nice catch. I was wondering why the tests were failing on the version I was running in terminal but not the one in atom, must have missed that char when copying between. Should pass now 🤞

**Comment by IanVS** [comment]
Actually, one more thing before I merge this, do you think you could add a regression test, based on the results that the jsdoc plugin is giving?  Then we'll be sure not to break this in the future.

**Comment by IanVS** [comment]
@mattlyons0 I haven't forgotten about this, just been busy.  I'll try to review in the next few days.  Thanks again.

**Comment by mattlyons0** [comment]
Looks like you are following a different commit format now, updated.
